<?php

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo '<br />';
echo $this->formRow($form->get('artist'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
// We can replace all the form-rendering echo statement with :
// echo $this->formCollection($form);
echo $this->form()->closeTag();
